config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }

  resources :users do
    collection do
      get 'dashboard'
    end
    resources :cvs do
      member do
        patch 'display_personal_information'
        patch 'display_styles'
        patch 'display_sections'
        post 'download_pdf'
        patch 'set_style'
        get 'style1'
      end
      resources :sections do
        member do
          patch 'move_section_up'
          patch 'move_section_down'
        end
        resources :certificates do
          member do
            patch 'move_certificate_up'
            patch 'move_certificate_down'
          end
        end
        resources :courses do
          member do
            patch 'move_course_up'
            patch 'move_course_down'
          end
        end
        resources :educations do
          member do
            patch 'move_education_up'
            patch 'move_education_down'
          end
        end
        resources :employments do
          member do
            patch 'move_employment_up'
            patch 'move_employment_down'
          end
        end
        resources :languages do
          member do
            patch 'move_language_up'
            patch 'move_language_down'
          end
        end
        resources :references do
          member do
            patch 'move_reference_up'
            patch 'move_reference_down'
          end
        end
      end
    end
  end

  authenticated :user do
    root to: redirect('/users/dashboard'), as: :authenticated_user_root
  end
  unauthenticated :user do
    devise_scope :user do
      get '/' => 'devise/sessions#new'
    end
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :cv
  has_many :certificates, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :employments, dependent: :destroy
  has_many :languages, dependent: :destroy
  has_many :references, dependent: :destroy

  has_rich_text :content

  enum name: {
    certificates_section: 0,
    courses_section: 1,
    educations_section: 2,
    employments_section: 3,
    languages_section: 4,
    references_section: 5,
    skills_section: 6,
    interest_section: 7,
    privacy_policy_sections: 8,
    description_section: 9,
    custom_section: 10
  }
  NAMES = names.to_h { |k, _v| [k.to_sym, k] }.freeze

  enum horizontal_position: {
    main_body: 0,
    side_body: 1
  }
  HORIZONTAL_POSITIONS = horizontal_positions.to_h { |k, _v| [k.to_sym, k] }.freeze

  def self.get_names
    NAMES
  end

  def self.get_horizontal_positions
    HORIZONTAL_POSITIONS
  end

  def self.get_human_names
    NAMES.to_h { |k, _v| [Section.human_enum_name(:names, k), k] }
  end

  def self.get_human_horizontal_positions
    HORIZONTAL_POSITIONS.to_h { |k, _v| [Section.human_enum_name(:horizontal_positions, k), k] }
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  load_and_authorize_resource

  def create
    @cv = Cv.find(params[:cv_id])
    vertical_position = @cv.sections.where(horizontal_position: Section.horizontal_positions[:main_body]).size + 1
    section = Section.new(sections_params(:cv))
    section.vertical_position = vertical_position
    section.cv_id = params[:cv_id]
    if section.save
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    else
      respond_to do |format|
        format.js { render 'sections/new_section_form.js.erb', layout: false }
      end
    end
  end

  def update
    @section = Section.find(params[:id])
    @cv = Cv.find(params[:cv_id])
    if @section.horizontal_position != sections_params(:section)[:horizontal_position]
      params[:section][:vertical_position] = @cv.sections.where(horizontal_position: sections_params(:section)[:horizontal_position]).size + 1
    end
    if @section.update(sections_params(:section))
      assure_position_consistancy
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  def destroy
    @cv = Cv.find(params[:cv_id])
    @section = Section.find(params[:id])
    @section.destroy
    assure_position_consistancy
    respond_to do |format|
      format.js { render 'sections/sections_list.js.erb', layout: false }
    end
  end

  def move_section_up
    @cv = Cv.find(params[:cv_id])
    @section = Section.find(params[:id])
    up_section = @cv.sections.find_by(horizontal_position: @section.horizontal_position, vertical_position: @section.vertical_position - 1)
    if up_section.present?
      @section.update(vertical_position: @section.vertical_position - 1)
      up_section.update(vertical_position: up_section.vertical_position + 1)
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  def move_section_down
    @cv = Cv.find(params[:cv_id])
    @section = Section.find(params[:id])
    down_section = @cv.sections.find_by(horizontal_position: @section.horizontal_position, vertical_position: @section.vertical_position + 1)
    if down_section.present?
      @section.update(vertical_position: @section.vertical_position + 1)
      down_section.update(vertical_position: down_section.vertical_position - 1)
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  private

  def assure_position_consistancy
    main_body_sections = @cv&.sections&.where(horizontal_position: Section.horizontal_positions[:main_body])
    side_body_sections = @cv&.sections&.where(horizontal_position: Section.horizontal_positions[:side_body])
    main_body_sections.order(:vertical_position).each.with_index(1) do |section, index|
      section.vertical_position = index
      section.save
    end
    side_body_sections.order(:vertical_position).each.with_index(1) do |section, index|
      section.vertical_position = index
      section.save
    end
  end

  def sections_params(required_symbol)
    return unless params.key?(required_symbol)

    params.require(required_symbol).permit(
      :name,
      :vertical_position,
      :custom_name,
      :content,
      :horizontal_position
    )
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_certificates_form.html.erb
<div class="section-container <%= section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side #{section.name}" : section.name%>" id="form-container">
  <%= simple_form_for section, url: user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <label class="title"><%= t(".#{section.name}_name") %></label>
    <div class="header">
      <div class="custom-name-container">
        <%= f.input :custom_name, class: 'form-control', label: false, placeholder: t(".custom_name"), input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <div class="position-dropdown">
        <%= f.input :horizontal_position, as: :select, collection: Section.get_human_horizontal_positions, class: 'form-control', required: false, include_blank: false, label: false, input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <%= render partial: 'sections/section_buttons', locals: { section: section } %>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.add_section'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
  <div class="certificates-container">
    <%= render partial: 'certificates/certificates_list', locals: { section: section } %>
  </div>
</div>

app/views/sections/_courses_form.html.erb
<div class="section-container <%= section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side #{section.name}" : section.name%>" id="form-container">
  <%= simple_form_for section, url: user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <label class="title"><%= t(".#{section.name}_name") %></label>
    <div class="header">
      <div class="custom-name-container">
        <%= f.input :custom_name, class: 'form-control', label: false, placeholder: t(".custom_name"), input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <div class="position-dropdown">
        <%= f.input :horizontal_position, as: :select, collection: Section.get_human_horizontal_positions, class: 'form-control', required: false, include_blank: false, label: false, input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <%= render partial: 'sections/section_buttons', locals: { section: section } %>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.add_section'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
  <div class="courses-container">
    <%= render partial: 'courses/courses_list', locals: { section: section } %>
  </div>
</div>

app/views/sections/_default_form.html.erb
<div class="section-container <%= section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side #{section.name}" : section.name%>" id="form-container" id="form-container">
  <%= simple_form_for section, url: user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <label class="title"><%= t(".#{section.name}_name") %></label>
    <div class="header">
      <div class="custom-name-container">
        <%= f.input :custom_name, class: 'form-control', label: false, placeholder: t(".#{section.name}_custom_name"), input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <div class="position-dropdown">
        <%= f.input :horizontal_position, as: :select, collection: Section.get_human_horizontal_positions, class: 'form-control', required: false, include_blank: false, label: false, input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <%= render partial: 'sections/section_buttons', locals: { section: section } %>
    </div>
    <%= f.input :content, as: :rich_text_area, class: 'form-control', label: false, placeholder: t(".#{section.name}_description"), input_html: { onchange: "submitSectionOnChange(this)" } %>
    <div class="form-group submit hidden">
      <%= f.submit t('.add_section'), id: "submit-button", class: 'add-section-button'%>
    </div>
  <% end %>
</div>

app/views/sections/_educations_form.html.erb
<div class="section-container <%= section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side #{section.name}" : section.name%>" id="form-container">
  <%= simple_form_for section, url: user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <label class="title"><%= t(".#{section.name}_name") %></label>
    <div class="header">
      <div class="custom-name-container">
        <%= f.input :custom_name, class: 'form-control', label: false, placeholder: t(".custom_name"), input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <div class="position-dropdown">
        <%= f.input :horizontal_position, as: :select, collection: Section.get_human_horizontal_positions, class: 'form-control', required: false, include_blank: false, label: false, input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <%= render partial: 'sections/section_buttons', locals: { section: section } %>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.add_section'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
  <div class="educations-container">
    <%= render partial: 'educations/educations_list', locals: { section: section } %>
  </div>
</div>

app/views/sections/_employments_form.html.erb
<div class="section-container <%= section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side #{section.name}" : section.name%>" id="form-container">
  <%= simple_form_for section, url: user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <label class="title"><%= t(".#{section.name}_name") %></label>
    <div class="header">
      <div class="custom-name-container">
        <%= f.input :custom_name, class: 'form-control', label: false, placeholder: t(".custom_name"), input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <div class="position-dropdown">
        <%= f.input :horizontal_position, as: :select, collection: Section.get_human_horizontal_positions, class: 'form-control', required: false, include_blank: false, label: false, input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <%= render partial: 'sections/section_buttons', locals: { section: section } %>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.add_section'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
  <div class="employments-container">
    <%= render partial: 'employments/employments_list', locals: { section: section } %>
  </div>
</div>

app/views/sections/_languages_form.html.erb
<div class="section-container <%= section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side #{section.name}" : section.name%>" id="form-container">
  <%= simple_form_for section, url: user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <label class="title"><%= t(".#{section.name}_name") %></label>
    <div class="header">
      <div class="custom-name-container">
        <%= f.input :custom_name, class: 'form-control', label: false, placeholder: t(".custom_name"), input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <div class="position-dropdown">
        <%= f.input :horizontal_position, as: :select, collection: Section.get_human_horizontal_positions, class: 'form-control', required: false, include_blank: false, label: false, input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <%= render partial: 'sections/section_buttons', locals: { section: section } %>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.add_section'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
  <div class="languages-container">
    <%= render partial: 'languages/languages_list', locals: { section: section } %>
  </div>
</div>

app/views/sections/_new_section_form.html.erb
<div class="sections-container">
  <%= simple_form_for @cv, url: user_cv_sections_path(user_id: current_user.id, cv_id: @cv.id), method: :post, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <label class="title section"><%= t('.sections') %></label>
    <div class="sections-dropdown">
      <%= f.input :name, as: :select, collection: @cv.get_available_human_names, class: 'form-control', required: false, include_blank: false, label: false %>
    </div>
    <div class="form-group submit">
      <div class="dropdown show">
        <%= f.submit t('.add_section'), class: 'add-section-button' %>
        <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
          <%= t('.add_new_section') %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="buttons-container">
  <div class="dropdown show">
    <%= link_to display_personal_information_user_cv_path(user_id: current_user.id, id: @cv.id), method: :patch, class: 'back-button', remote: true do %>
      <%= inline_svg_tag 'back-icon.svg', class:"icon white round-button large" %>
    <% end %>
    <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
      <%= t('.back') %>
    </div>
  </div>
  <div class="dropdown show">
    <%= link_to display_styles_user_cv_path(user_id: current_user.id, id: @cv.id), method: :patch, class: 'next-button', remote: true do %>
      <%= inline_svg_tag 'next-icon.svg', class:"icon white round-button large" %>
    <% end %>
    <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="goToStylesDropdownMenu">
      <%= t('.next') %>
    </div>
  </div>
</div>

app/views/sections/_references_form.html.erb
<div class="section-container <%= section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side #{section.name}" : section.name%>" id="form-container">
  <%= simple_form_for section, url: user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <label class="title"><%= t(".#{section.name}_name") %></label>
    <div class="header">
      <div class="custom-name-container">
        <%= f.input :custom_name, class: 'form-control', label: false, placeholder: t(".custom_name"), input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <div class="position-dropdown">
        <%= f.input :horizontal_position, as: :select, collection: Section.get_human_horizontal_positions, class: 'form-control', required: false, include_blank: false, label: false, input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <%= render partial: 'sections/section_buttons', locals: { section: section } %>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.add_section'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
  <div class="references-container">
    <%= render partial: 'references/references_list', locals: { section: section } %>
  </div>
</div>

app/views/sections/_section_buttons.html.erb
<div class="section-buttons-container">
  <% if section.vertical_position > 1 %>
    <div class="dropdown show">
      <%= link_to move_section_up_user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, class: 'section-up', remote: true do %>
        <%= inline_svg_tag "up-arrow.svg", class:"icon white round-button" %>
      <% end %>
      <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
        <%= t('.move_section_up') %>
      </div>
    </div>
  <% end %>
  <% if section.vertical_position < @cv.sections.where(horizontal_position: section.horizontal_position).size %>
    <div class="dropdown show">
      <%= link_to move_section_down_user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :patch, class: 'section-down', remote: true do %>
        <%= inline_svg_tag "down-arrow.svg", class:"icon white round-button" %>
      <% end %>
      <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
        <%= t('.move_section_down') %>
      </div>
    </div>
  <% end %>
  <div class="dropdown show">
    <%= link_to user_cv_section_path(user_id: current_user.id, cv_id: @cv.id, id: section.id), method: :delete, class: 'delete-section', remote: true do %>
      <%= inline_svg_tag "close-icon.svg", class:"icon white round-button" %>
    <% end %>
    <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
      <%= t('.delete_section') %>
    </div>
  </div>
</div>

app/views/sections/_sections_list.html.erb
<% @cv.sections.order(:horizontal_position, :vertical_position).each do |section|%>
  <% if section.name == Section.get_names[:certificates_section] %>
    <%= render partial: 'sections/certificates_form', locals: { section: section } %>
  <% elsif section.name == Section.get_names[:courses_section] %>
    <%= render partial: 'sections/courses_form', locals: { section: section } %>
  <% elsif section.name == Section.get_names[:educations_section] %>
    <%= render partial: 'sections/educations_form', locals: { section: section } %>
  <% elsif section.name == Section.get_names[:employments_section] %>
    <%= render partial: 'sections/employments_form', locals: { section: section } %>
  <% elsif section.name == Section.get_names[:languages_section] %>
    <%= render partial: 'sections/languages_form', locals: { section: section } %>
  <% elsif section.name == Section.get_names[:references_section] %>
    <%= render partial: 'sections/references_form', locals: { section: section } %>
  <% else %>
    <%= render partial: 'sections/default_form', locals: { section: section } %>
  <% end %>
<% end %>

app/views/sections/new_section_form.js.erb
if (document.querySelector('#sections-form')) {
  document.querySelector('#sections-form').innerHTML = "<%= j render(partial: 'new_section_form'); %>"
}

app/views/sections/sections_list.js.erb
if (document.querySelector('#sections-list')) {
  document.querySelector('#sections-list').innerHTML = "<%= j render(partial: 'sections/sections_list'); %>"
  assignOnChangeToTrix();
}
if (document.querySelector('#sections-form')) {
  document.querySelector('#sections-form').innerHTML = "<%= j render(partial: 'sections/new_section_form'); %>"
}