config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }

  resources :users do
    collection do
      get 'dashboard'
    end
    resources :cvs do
      member do
        patch 'display_personal_information'
        patch 'display_styles'
        patch 'display_sections'
        post 'download_pdf'
        patch 'set_style'
        get 'style1'
      end
      resources :sections do
        member do
          patch 'move_section_up'
          patch 'move_section_down'
        end
        resources :certificates do
          member do
            patch 'move_certificate_up'
            patch 'move_certificate_down'
          end
        end
        resources :courses do
          member do
            patch 'move_course_up'
            patch 'move_course_down'
          end
        end
        resources :educations do
          member do
            patch 'move_education_up'
            patch 'move_education_down'
          end
        end
        resources :employments do
          member do
            patch 'move_employment_up'
            patch 'move_employment_down'
          end
        end
        resources :languages do
          member do
            patch 'move_language_up'
            patch 'move_language_down'
          end
        end
        resources :references do
          member do
            patch 'move_reference_up'
            patch 'move_reference_down'
          end
        end
      end
    end
  end

  authenticated :user do
    root to: redirect('/users/dashboard'), as: :authenticated_user_root
  end
  unauthenticated :user do
    devise_scope :user do
      get '/' => 'devise/sessions#new'
    end
  end
end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :section

  has_rich_text :description

  def move_up
    up_reference = section.references.find_by(position: position - 1)
    if up_reference.present?
      update(position: position - 1)
      up_reference.update(position: up_reference.position + 1)
    end
  end

  def move_down
    down_reference = section.references.find_by(position: position + 1)
    if down_reference.present?
      update(position: position + 1)
      down_reference.update(position: down_reference.position - 1)
    end
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  load_and_authorize_resource
  before_action :set_cv_and_section

  def create
    Reference.create(section_id: @section.id, position: @section.references.size + 1)
    respond_to do |format|
      format.js { render 'sections/sections_list.js.erb', layout: false }
    end
  end

  def update
    if @reference.update(references_params)
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  def destroy
    @reference.destroy
    respond_to do |format|
      format.js { render 'sections/sections_list.js.erb', layout: false }
    end
  end

  def move_reference_up
    if @reference.move_up
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  def move_reference_down
    if @reference.move_down
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  private

  def set_cv_and_section
    @cv = Cv.find(params[:cv_id])
    @section = Section.find(params[:section_id])
  end

  def references_params
    return unless params.key?(:reference)

    params.require(:reference).permit(
      :company,
      :contact_person,
      :phone_number,
      :email,
      :description,
      :position
    )
  end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<div class="reference-form" id="form-container">
  <%= simple_form_for reference, url: user_cv_section_reference_path(user_id: current_user.id, cv_id: @cv.id, section_id: reference.section_id, id: reference.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="reference-box">
      <div class="reference-container">
        <div class="row">
          <%= f.input :company, class: 'form-control', label: false, placeholder: t(".company"), input_html: { onchange: "submitSectionOnChange(this)" } %>
          <%= f.input :contact_person, class: 'form-control', label: false, placeholder: t(".contact_person"), input_html: { onchange: "submitSectionOnChange(this)" } %>
        </div>
        <div class="row">
          <%= f.input :phone_number, class: 'form-control', label: false, placeholder: t(".phone_number"), input_html: { onchange: "submitSectionOnChange(this)" } %>
          <%= f.input :email, class: 'form-control', label: false, placeholder: t(".email"), input_html: { onchange: "submitSectionOnChange(this)" } %>
        </div>
        <div class="row">
          <%= f.input :description, as: :rich_text_area, class: 'form-control', label: false, placeholder: t(".description"), input_html: { onchange: "submitSectionOnChange(this)" } %>
        </div>
      </div>
      <div class="reference-buttons">
        <div class="dropdown show">
          <%= link_to user_cv_section_reference_path(user_id: current_user.id, cv_id: @cv.id, section_id: reference.section_id, id: reference.id), method: :delete, class: 'delete-reference', remote: true do %>
            <%= inline_svg_tag "close-icon.svg", class:"icon green buttons delete" %>
          <% end %>
          <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.delete') %>
          </div>
        </div>
        <% if reference.position > 1 %>
          <div class="dropdown show">
            <%= link_to move_reference_up_user_cv_section_reference_path(user_id: current_user.id, cv_id: @cv.id, section_id: reference.section_id, id: reference.id), method: :patch, class: 'move-up-reference', remote: true do %>
              <%= inline_svg_tag "up-arrow.svg", class:"icon green buttons" %>
            <% end %>
            <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.move_up') %>
          </div>
        </div>
        <% end %>
        <% if reference.position < section.references.size %>
          <div class="dropdown show">
            <%= link_to move_reference_down_user_cv_section_reference_path(user_id: current_user.id, cv_id: @cv.id, section_id: reference.section_id, id: reference.id), method: :patch, class: 'move-down-reference', remote: true do %>
              <%= inline_svg_tag "down-arrow.svg", class:"icon green buttons" %>
            <% end %>
            <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.move_down') %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.update'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
</div>

app/views/references/_references_list.html.erb
<% section.references.order(:position).each do |reference|%>
  <%= render partial: 'references/form', locals: { section: section, reference: reference } %>
<% end %>
<div class="button-container">
  <div class="dropdown show">
    <%= link_to user_cv_section_references_path(user_id: current_user.id, cv_id: @cv.id, section_id: section.id), method: :post, class: "add-reference #{section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side" : ""}", remote: true do %>
      <%= inline_svg_tag 'plus-icon.svg', class:"icon white round-button section #{section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side" : ""}" %>
    <% end %>
    <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
      <%= t('.add_reference') %>
    </div>
  </div>
</div>