config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }

  resources :users do
    collection do
      get 'dashboard'
    end
    resources :cvs do
      member do
        patch 'display_personal_information'
        patch 'display_styles'
        patch 'display_sections'
        post 'download_pdf'
        patch 'set_style'
        get 'style1'
      end
      resources :sections do
        member do
          patch 'move_section_up'
          patch 'move_section_down'
        end
        resources :certificates do
          member do
            patch 'move_certificate_up'
            patch 'move_certificate_down'
          end
        end
        resources :courses do
          member do
            patch 'move_course_up'
            patch 'move_course_down'
          end
        end
        resources :educations do
          member do
            patch 'move_education_up'
            patch 'move_education_down'
          end
        end
        resources :employments do
          member do
            patch 'move_employment_up'
            patch 'move_employment_down'
          end
        end
        resources :languages do
          member do
            patch 'move_language_up'
            patch 'move_language_down'
          end
        end
        resources :references do
          member do
            patch 'move_reference_up'
            patch 'move_reference_down'
          end
        end
      end
    end
  end

  authenticated :user do
    root to: redirect('/users/dashboard'), as: :authenticated_user_root
  end
  unauthenticated :user do
    devise_scope :user do
      get '/' => 'devise/sessions#new'
    end
  end
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :section

  has_rich_text :description

  def move_up
    up_certificate = section.certificates.find_by(position: position - 1)
    if up_certificate.present?
      update(position: position - 1)
      up_certificate.update(position: up_certificate.position + 1)
    end
  end

  def move_down
    down_certificate = section.certificates.find_by(position: position + 1)
    if down_certificate.present?
      update(position: position + 1)
      down_certificate.update(position: down_certificate.position - 1)
    end
  end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  load_and_authorize_resource
  before_action :set_cv_and_section

  def create
    Certificate.create(section_id: @section.id, position: @section.certificates.size + 1)
    respond_to do |format|
      format.js { render 'sections/sections_list.js.erb', layout: false }
    end
  end

  def update
    if @certificate.update!(certificates_params)
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  def destroy
    @certificate.destroy
    respond_to do |format|
      format.js { render 'sections/sections_list.js.erb', layout: false }
    end
  end

  def move_certificate_up
    if @certificate.move_up
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  def move_certificate_down
    if @certificate.move_down
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  private

  def set_cv_and_section
    @cv = Cv.find(params[:cv_id])
    @section = Section.find(params[:section_id])
  end

  def certificates_params
    return unless params.key?(:certificate)

    params.require(:certificate).permit(
      :name,
      :date,
      :description,
      :position
    )
  end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_certificates_list.html.erb
<% section.certificates.order(:position).each do |certificate|%>
  <%= render partial: 'certificates/form', locals: { section: section, certificate: certificate } %>
<% end %>
<div class="button-container">
  <div class="dropdown show">
    <%= link_to user_cv_section_certificates_path(user_id: current_user.id, cv_id: @cv.id, section_id: section.id), method: :post, class: "add-certificate #{section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side" : ""}", remote: true do %>
      <%= inline_svg_tag 'plus-icon.svg', class:"icon white round-button section #{section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side" : ""}" %>
    <% end %>
    <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
      <%= t('.add_certificate') %>
    </div>
  </div>
</div>

app/views/certificates/_form.html.erb
<div class="certificate-form" id="form-container">
  <%= simple_form_for certificate, url: user_cv_section_certificate_path(user_id: current_user.id, cv_id: @cv.id, section_id: certificate.section_id, id: certificate.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="certificate-box">
      <div class="certificate-container">
        <div class="row">
          <%= f.input :name, class: 'form-control', label: false, placeholder: t(".name"), input_html: { onchange: "submitSectionOnChange(this)" } %>
          <div class="date-container">
            <label><%= t('.date') %></label>
            <%= f.input :date, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year, order: [:month, :year], class: 'form-control', label: false, input_html: { onchange: "submitSectionOnChange(this)" }   %>
          </div>
        </div>
        <%= f.input :description, as: :rich_text_area, class: 'form-control', label: false, placeholder: t(".description"), input_html: { onchange: "submitSectionOnChange(this)" } %>
      </div>
      <div class="certificate-buttons">
        <div class="dropdown show">
          <%= link_to user_cv_section_certificate_path(user_id: current_user.id, cv_id: @cv.id, section_id: certificate.section_id, id: certificate.id), method: :delete, class: 'delete-certificate', remote: true do %>
            <%= inline_svg_tag "close-icon.svg", class:"icon green buttons delete" %>
          <% end %>
          <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.delete') %>
          </div>
        </div>
        <% if certificate.position > 1 %>
          <div class="dropdown show">
            <%= link_to move_certificate_up_user_cv_section_certificate_path(user_id: current_user.id, cv_id: @cv.id, section_id: certificate.section_id, id: certificate.id), method: :patch, class: 'move-up-certificate', remote: true do %>
              <%= inline_svg_tag "up-arrow.svg", class:"icon green buttons" %>
            <% end %>
            <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.move_up') %>
          </div>
        </div>
        <% end %>
        <% if certificate.position < section.certificates.size %>
          <div class="dropdown show">
            <%= link_to move_certificate_down_user_cv_section_certificate_path(user_id: current_user.id, cv_id: @cv.id, section_id: certificate.section_id, id: certificate.id), method: :patch, class: 'move-down-certificate', remote: true do %>
              <%= inline_svg_tag "down-arrow.svg", class:"icon green buttons" %>
            <% end %>
            <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.move_down') %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.update'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
</div>