config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }

  resources :users do
    collection do
      get 'dashboard'
    end
    resources :cvs do
      member do
        patch 'display_personal_information'
        patch 'display_styles'
        patch 'display_sections'
        post 'download_pdf'
        patch 'set_style'
        get 'style1'
      end
      resources :sections do
        member do
          patch 'move_section_up'
          patch 'move_section_down'
        end
        resources :certificates do
          member do
            patch 'move_certificate_up'
            patch 'move_certificate_down'
          end
        end
        resources :courses do
          member do
            patch 'move_course_up'
            patch 'move_course_down'
          end
        end
        resources :educations do
          member do
            patch 'move_education_up'
            patch 'move_education_down'
          end
        end
        resources :employments do
          member do
            patch 'move_employment_up'
            patch 'move_employment_down'
          end
        end
        resources :languages do
          member do
            patch 'move_language_up'
            patch 'move_language_down'
          end
        end
        resources :references do
          member do
            patch 'move_reference_up'
            patch 'move_reference_down'
          end
        end
      end
    end
  end

  authenticated :user do
    root to: redirect('/users/dashboard'), as: :authenticated_user_root
  end
  unauthenticated :user do
    devise_scope :user do
      get '/' => 'devise/sessions#new'
    end
  end
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :section

  def move_up
    up_education = section.educations.find_by(position: position - 1)
    if up_education.present?
      update(position: position - 1)
      up_education.update(position: up_education.position + 1)
    end
  end

  def move_down
    down_education = section.educations.find_by(position: position + 1)
    if down_education.present?
      update(position: position + 1)
      down_education.update(position: down_education.position - 1)
    end
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_cv_and_section

  def create
    Education.create(section_id: @section.id, position: @section.educations.size + 1)
    respond_to do |format|
      format.js { render 'sections/sections_list.js.erb', layout: false }
    end
  end

  def update
    if @education.update(educations_params)
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  def destroy
    @education.destroy
    respond_to do |format|
      format.js { render 'sections/sections_list.js.erb', layout: false }
    end
  end

  def move_education_up
    if @education.move_up
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  def move_education_down
    if @education.move_down
      respond_to do |format|
        format.js { render 'sections/sections_list.js.erb', layout: false }
      end
    end
  end

  private

  def set_cv_and_section
    @cv = Cv.find(params[:cv_id])
    @section = Section.find(params[:section_id])
  end

  def educations_params
    return unless params.key?(:education)

    assure_end_date_format(params.require(:education).permit(
                             :level,
                             :city,
                             :university,
                             :faculty,
                             :specialisation,
                             :position,
                             :start_date,
                             :end_date
    ), @education.end_date)
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_educations_list.html.erb
<% section.educations.order(:position).each do |education|%>
  <%= render partial: 'educations/form', locals: { section: section, education: education } %>
<% end %>
<div class="button-container">
  <div class="dropdown show">
    <%= link_to user_cv_section_educations_path(user_id: current_user.id, cv_id: @cv.id, section_id: section.id), method: :post, class: "add-education #{section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side" : ""}", remote: true do %>
      <%= inline_svg_tag 'plus-icon.svg', class:"icon white round-button section #{section.horizontal_position == Section.get_horizontal_positions[:side_body] ? "side" : ""}" %>
    <% end %>
    <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
      <%= t('.add_education') %>
    </div>
  </div>
</div>

app/views/educations/_form.html.erb
<div class="education-form" id="form-container">
  <%= simple_form_for education, url: user_cv_section_education_path(user_id: current_user.id, cv_id: @cv.id, section_id: education.section_id, id: education.id), method: :patch, remote: true, html: { class: 'customized record-form' } do |f| %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="education-box">
      <div class="education-container">
        <div class="row">
          <%= f.input :level, class: 'form-control', label: false, placeholder: t(".level"), input_html: { onchange: "submitSectionOnChange(this)" } %>
          <%= f.input :city, class: 'form-control', label: false, placeholder: t(".city"), input_html: { onchange: "submitSectionOnChange(this)" } %>
        </div>
        <div class="row">
          <%= f.input :university, class: 'form-control', label: false, placeholder: t(".university"), input_html: { onchange: "submitSectionOnChange(this)" } %>
        </div>
        <div class="row">
          <%= f.input :faculty, class: 'form-control', label: false, placeholder: t(".faculty"), input_html: { onchange: "submitSectionOnChange(this)" } %>
          <%= f.input :specialisation, class: 'form-control', label: false, placeholder: t(".specialisation"), input_html: { onchange: "submitSectionOnChange(this)" } %>
        </div>
        <div class="row dates">
          <div class="date-container">
            <label><%= t('.start_date') %></label>
            <%= f.input :start_date, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year, order: [:month, :year], class: 'form-control', label: false, input_html: { onchange: "submitSectionOnChange(this)" } %>
          </div>
          <div class="date-container">
            <label><%= t('.end_date') %></label>
            <%= f.input :end_date, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year, order: [:month, :year], class: 'form-control', label: false, include_blank: true, input_html: { onchange: "submitSectionOnChange(this)" } %>
          </div>
        </div>
      </div>
      <div class="education-buttons">
        <div class="dropdown show">
          <%= link_to user_cv_section_education_path(user_id: current_user.id, cv_id: @cv.id, section_id: education.section_id, id: education.id), method: :delete, class: 'delete-education', remote: true do %>
            <%= inline_svg_tag "close-icon.svg", class:"icon green buttons delete" %>
          <% end %>
          <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.delete') %>
          </div>
        </div>
        <% if education.position > 1 %>
          <div class="dropdown show">
            <%= link_to move_education_up_user_cv_section_education_path(user_id: current_user.id, cv_id: @cv.id, section_id: education.section_id, id: education.id), method: :patch, class: 'move-up-education', remote: true do %>
              <%= inline_svg_tag "up-arrow.svg", class:"icon green buttons" %>
            <% end %>
            <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.move_up') %>
          </div>
        </div>
        <% end %>
        <% if education.position < section.educations.size %>
          <div class="dropdown show">
            <%= link_to move_education_down_user_cv_section_education_path(user_id: current_user.id, cv_id: @cv.id, section_id: education.section_id, id: education.id), method: :patch, class: 'move-down-education', remote: true do %>
              <%= inline_svg_tag "down-arrow.svg", class:"icon green buttons" %>
            <% end %>
            <div style="padding: 15px;" class="dropdown-menu" aria-labelledby="backToSectionsDropdownMenu">
            <%= t('.move_down') %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="form-group submit hidden">
      <%= f.submit t('.update'), id: "submit-button", class: 'add-section-button' %>
    </div>
  <% end %>
</div>